[project]
name = "ai-agentic-software-dev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=11.3.0",
    "transformers>=4.56.0",
]
